### ISSUE TITLE
2 (maybe 3?) Very Minor Glitches

### ISSUE THREAD

**Issue by Something-Went-Terribly-Wrong** [esapee/Essence-Armory#4]
When you have adventures gear enabled it still shows the health boosting belts as an option, but when you click on it nei brings up the health boosting vambraces. Along with that, trying to infuse the belt with the health boost it says "invalid infusion recipe" (only with adventures gear enabled).

And for the second glitch, the vambraces and pauldrons don't have any texture, it just shows up as a purple and black checkerboard.

Lastly, this may not be glitch, but there is no essence infused cloak.

**Comment by Something-Went-Terribly-Wrong** [comment]
Btw I am referring to the very latest 1.7.10 update (that you made for me <3)

**Comment by murapix** [comment]
1. Huh, I thought I'd already dealt with that stuff. I guess I forgot to do it for belts. At the rate you're putting out errors, it might actually be a good idea to leave it for a couple, especially since this one isn't game-breaking.
2. Yeah, I never did get a texture for those two. My texture artist moved on, and I changed to working on 1.8.9. I could just pull an image off google, but once again, not a critical error. I guess that makes enough errors to put out a version though. Give me a few minutes to get that out.
3. I didn't ever make a cloak; I just didn't have any upgrades that would fit on them better than on another piece of equipment.

**Comment by murapix** [comment]
Ok, just put out yet another version with those things fixed. Keep letting me know as you find them - even if the mod isn't really developed anymore, I want my current players to have the best experience they can with it.

**Comment by Something-Went-Terribly-Wrong** [comment]
Hey if you want, I could do a few half-assed textures. And maybe you could add the cloak for the whole "full set" look :D 

I'll make a new issue later with just the new textures k? <3

**Comment by murapix** [comment]
Nah, I just half-assed the textures myself, which are part of this last release. I'd add the cloak in, but I don't really want to add anything to the mod without having a use for it. I'm also largely focusing on creating another mod at this point, and once I'm done with that, I'm going to be completely recreating Essence Armory from the ground up.

I will be keeping most of the current upgrade system, that part I've only heard good feedback on, but there's a lot of empty space between starting the mod and actually making anything upgradeable that I want to use for more content.
